# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "github-actions" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: 'eslint'
        update-types: ['version-update:semver-major'] # Ignore major version updates for eslint
    groups:
      nextjs:
        patterns:
          - "@cloudflare/next-on-pages"
          - "@next/*"
          - "eslint-config-next"
          - "next"
          - "vercel"
          - "wrangler"
      typescript:
        patterns:
          - "@typescript-eslint/*"
          - "@types/*"
          - "@webgpu/types"
          - "eslint"
          - "eslint-config-prettier"
          - "eslint-plugin-*"
          - "prettier*"
          - "typescript"
